name: Feature
run-name: Feature

on:
  pull_request:
    branches:
      - main

jobs:
  
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "============="
          echo "=== Debug ==="
          echo "============="
          echo "github ref: " ${{ vars.GITHUB_REF }}
          echo "dotnet version: " ${{ vars.DOTNET_VERSION }}
          echo "event name: " ${{ github.event_name }}
          
  frontend:
    name: EG.Frontend
    runs-on: ubuntu-latest
    needs: debug
    
    steps:
      - uses: actions/checkout@v3

      - name: Setting up Dotnet with ${{ vars.DOTNET_VERSION }} version
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: EG Nuget repo
        run: |
          dotnet nuget add source --username Andras-Csanyi --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/EncyclopediaGalactica/index.json"

      - name: Restore
        run: |
          dotnet restore FrontEnd.sln

      - name: Build
        run: |
          dotnet build --configuration Debug FrontEnd.sln

      - name: Test
        run: |
          dotnet test --no-restore --verbosity normal FrontEnd.sln
